main: su.nightexpress.excellentcrates.ExcellentCrates
version: '${project.version}'
name: ExcellentCrates
author: NightExpress
desciption: Fully customizable crates with rewards. Enjoy.
depend: [ NexEngine ]
softdepend: [ HolographicDisplays, DecentHolograms, Vault, PlaceholderAPI ]
api-version: 1.17